
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Daniel Tenecora
 */
public class Deterministico extends javax.swing.JFrame {

    /**
     * Creates new form Deterministico
     */
    static String simbolos = "";
    static int numestados = 0;
    static ArrayList estados = new ArrayList();
    static String esinicial = "";
    static ArrayList estadosaceptacion = new ArrayList();

    public Deterministico() {
        setTitle("AFD");
        initComponents();
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                new Interfaz().setVisible(true);
                dispose();
            }
        });
    }

 //<-------------------------------------------------------------------------------------------------------------------------------------->
    // Funcion que verifica que sea un numero el numero de estados
    public boolean isNumber(String num) {
        try {
            Integer.parseInt(num);
            return true;
        } catch (NumberFormatException nfe) {
            return false;
        }
    }
  
//<-------------------------------------------------------------------------------------------------------------------------------------->
    // Validacion para el numero de estados
    public int validacion() {
        int numero1 = 0;
        int numero = 0;
        boolean bandera = false;
        String num;
        num = JOptionPane.showInputDialog(null, "Ingrese el numero de estados:");
        if (num == null) {
            JOptionPane.showMessageDialog(null, "Se ha cancelado la operacion");
        } else {
            if (!isNumber(num)) {
                do {
                    num = JOptionPane.showInputDialog(null, "Debe ingresar un numero", "Erro!", JOptionPane.ERROR_MESSAGE);
                    if (num == null) {
                        JOptionPane.showMessageDialog(null, "Se ha cancelado la operacion");
                        bandera = true;
                        break;
                    }
                } while (!isNumber(num));
            }
            if (bandera == false) {
                numero = Integer.parseInt(num);
                if (numero < 1) {
                    do {
                        num = JOptionPane.showInputDialog(null, "El numero de estados debe ser > 0", "Error!", JOptionPane.ERROR_MESSAGE);
                        if (num == null) {
                            JOptionPane.showMessageDialog(null, "Se ha cancelado la operacion");
                            bandera = true;
                            break;
                        }
                    } while (numero < 1);
                    if (bandera == false) {
                        numero = Integer.parseInt(num);
                    }
                }
            }
            numero1 = numero;
        }
        return numero1;
    }

//<-------------------------------------------------------------------------------------------------------------------------------------->
    // Funcuion que guarda los estados generados
    public void guardaestados(int numestados) {
        estados.removeAll(estados);
        String cadena = "q";
        if (numestados > 0) {
            for (int i = 0; i < numestados; i++) {
                cadena = cadena + i;
                estados.add(cadena);
                cadena = "q";
            }
            cadena = "{ ";
            for (Object estados1 : estados) {
                cadena = cadena + estados1.toString() + " ";
            }
            cadena = cadena + "}";
            JOptionPane.showMessageDialog(null, "Conjunto de estados: " + cadena);
        }
    }

//<-------------------------------------------------------------------------------------------------------------------------------------->    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Alfabeto = new javax.swing.JMenuItem();
        Estados = new javax.swing.JMenuItem();
        EstadoInicial = new javax.swing.JMenuItem();
        ConjuntoAceptación = new javax.swing.JMenuItem();
        TablaTransicion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        setResizable(false);

        jMenu1.setText("Ingreso");
        jMenu1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        Alfabeto.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Alfabeto.setText("Alfabeto");
        Alfabeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlfabetoActionPerformed(evt);
            }
        });
        jMenu1.add(Alfabeto);

        Estados.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Estados.setText("Estados");
        Estados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadosActionPerformed(evt);
            }
        });
        jMenu1.add(Estados);

        EstadoInicial.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        EstadoInicial.setText("Estado Inicial");
        EstadoInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadoInicialActionPerformed(evt);
            }
        });
        jMenu1.add(EstadoInicial);

        ConjuntoAceptación.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ConjuntoAceptación.setText("Estado/s Aceptación");
        ConjuntoAceptación.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConjuntoAceptaciónActionPerformed(evt);
            }
        });
        jMenu1.add(ConjuntoAceptación);

        TablaTransicion.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        TablaTransicion.setText("Tabla Transición");
        TablaTransicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TablaTransicionActionPerformed(evt);
            }
        });
        jMenu1.add(TablaTransicion);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AlfabetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlfabetoActionPerformed
        // TODO add your handling code here:
        Alfabeto alfabeto = new Alfabeto();
        alfabeto.setVisible(true);
    }//GEN-LAST:event_AlfabetoActionPerformed

    private void EstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadosActionPerformed
        // TODO add your handling code here:
        numestados = 0;
        numestados = validacion();
        guardaestados(numestados);
    }//GEN-LAST:event_EstadosActionPerformed

    private void TablaTransicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TablaTransicionActionPerformed
        // TODO add your handling code here:
        if (numestados == 0 || simbolos.equals("") || esinicial.equals("") || estadosaceptacion.size() == 0) {
            JOptionPane.showMessageDialog(null, "El albafeto esta vació o\nFalta el # de estados o \nFalta estado Inicial o \nFalta el estado de aceptacion", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        } else {
            TablaTransiciones tablatrans = new TablaTransiciones();
            tablatrans.setVisible(true);
        }
    }//GEN-LAST:event_TablaTransicionActionPerformed

    private void EstadoInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadoInicialActionPerformed
        // TODO add your handling code here:
        if (numestados == 0) {
            JOptionPane.showMessageDialog(null, "Debe ingresar el # de estados en Estados", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        } else {
            EstadoInicio estadoinicial = new EstadoInicio();
            estadoinicial.setVisible(true);
        }
    }//GEN-LAST:event_EstadoInicialActionPerformed

    private void ConjuntoAceptaciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConjuntoAceptaciónActionPerformed
        // TODO add your handling code here:
        if (numestados == 0) {
            JOptionPane.showMessageDialog(null, "Debe ingresar el # de estados en Estados", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        } else {
            EstadosFinales estadofinal = new EstadosFinales();
            estadofinal.setVisible(true);
        }
    }//GEN-LAST:event_ConjuntoAceptaciónActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Deterministico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Deterministico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Deterministico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Deterministico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Deterministico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Alfabeto;
    private javax.swing.JMenuItem ConjuntoAceptación;
    private javax.swing.JMenuItem EstadoInicial;
    private javax.swing.JMenuItem Estados;
    private javax.swing.JMenuItem TablaTransicion;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
